### ISSUE TITLE
Is it a way to run TomCat and other services on other ports?

### ISSUE THREAD

**Issue by xristos8574** [christophetd/log4shell-vulnerable-app#14]
I am trying to run this to evaluate a scanner, although I run it on another port rather than 8080 since I have some issues, TomCat runs on 8080. How could that be reconfigured ?

**Comment by christophetd** [comment]
You can change the Docker command to:

```
docker run --name vulnerable-app -p 8888:8080 ghcr.io/christophetd/log4shell-vulnerable-app
```

to make the application available on the port 8888 of the host so it doesn't conflict with your Tomcat.
