### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by dnsmichi** [christophetd/log4shell-vulnerable-app#16]
@christophetd Thanks for creating this great project for reproducing and mitigating the problem.

I'd suggest adding a LICENSE, MIT or Apache for example.

For context, we've imported your project to a GitLab.com project; I've added full kudos to you in https://gitlab.com/gitlab-de/playground/log4shell-vulnerable-app/-/merge_requests/2

**Comment by christophetd** [comment]
Done, thanks for the suggestion!
