### ISSUE TITLE
docker build problem on kali linux

### ISSUE THREAD

**Issue by okofishe** [christophetd/log4shell-vulnerable-app#23]
Hi,
Hello i have build this on both windows and mac without any problem. But when i trying building springboot via kali linux, i got this error message 👎 
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
[1/2] STEP 1/4: FROM gradle:7.3.1-jdk17-alpine AS builder
[2/2] STEP 1/5: FROM openjdk:8u181-jdk-alpine
Error: error creating build container: short-name "gradle:7.3.1-jdk17-alpine" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"

Can you please let me know the solution.
Thank you

**Comment by christophetd** [comment]
See https://github.com/containers/podman/issues/9390#issuecomment-876994582 for a potential fix. In any case, it's caused by your local setup and does not appear to be an issue with this repo
